project_id = "ufnxliieaejdvxcanqux"

[functions.form-webhook]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.insurance-webhook]
verify_jwt = false

[functions.credit-webhook]
verify_jwt = false

[functions.create-payment-link]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.payment-reminders]
verify_jwt = false

[functions.notify-vertriebler]
verify_jwt = false
